/**
 * timeline.js
 * High-precision animation timeline and audio-sync event manager
 */

export const BPM = 135.0;
export const SECONDS_PER_BEAT = 60.0 / BPM; // ~0.444s

export const SCENES = [
  {
    id: 'intro',
    start: 0.00,
    end: 0.67,
    title: 'Intro Peeking',
    charSprite1: 'char_intro_1',
    charSprite2: 'char_intro_2',
    charPos: { x: 30, y: 15 },
    textSprite: null,
    textPos: { x: 0, y: 0 },
    animType: 'blink_slow',
  },
  {
    id: 'my_heart',
    start: 0.67,
    end: 2.00,
    title: 'My Heart Skips A Beat',
    charSprite1: 'char_heart_1',
    charSprite2: 'char_heart_2',
    charPos: { x: 0, y: 65 },
    textSprite: 'text_heart',
    textPos: { x: 0, y: 6 },
    animType: 'heart_skip',
  },
  {
    id: 'walk_in_room',
    start: 2.00,
    end: 3.70,
    title: 'When You Walk In The Room',
    charSprite1: 'char_walk_1',
    charSprite2: 'char_walk_2',
    charPos: { x: 0, y: 55 },
    textSprite: 'text_walk',
    textPos: { x: 0, y: 6 },
    animType: 'walk_sway',
  },
  {
    id: 'i_go',
    start: 3.70,
    end: 4.30,
    title: 'I GO',
    charSprite1: 'char_boom_1',
    charSprite2: 'char_boom_2',
    charPos: { x: 0, y: 68 },
    textSprite: 'special_igo',
    textPos: { x: 10, y: 8 },
    animType: 'i_go_peek',
  },
  {
    id: 'boom',
    start: 4.30,
    end: 5.60,
    title: 'BOOM!',
    charSprite1: 'char_boom_1',
    charSprite2: 'char_boom_2',
    charPos: { x: 0, y: 68 },
    textSprite: null,
    textPos: { x: 0, y: 8 },
    animType: 'boom_hits',
    hits: [
      { time: 4.55, type: 'boom1', shake: 7 },
      { time: 4.97, type: 'boom2', shake: 9 },
      { time: 5.55, type: 'boom3', shake: 12 },
    ]
  },
  {
    id: 'you_go',
    start: 5.60,
    end: 5.93,
    title: 'YOU GO',
    charSprite1: 'special_zoom_flame_1',
    charSprite2: 'special_zoom_flame_2',
    charPos: { x: 0, y: 55 },
    textSprite: 'special_you_go',
    textPos: { x: 0, y: 6 },
    animType: 'you_go_burst',
  },
  {
    id: 'zoom',
    start: 5.93,
    end: 7.53,
    title: 'ZOOM Flame Burst',
    charSprite1: 'special_zoom_flame_1',
    charSprite2: 'special_zoom_flame_2',
    charPos: { x: 0, y: 45 },
    textSprite: null,
    textPos: { x: 0, y: 4 },
    animType: 'zoom_flame',
    subBeats: [5.93, 6.45, 6.98, 7.42]
  },
  {
    id: 'playboy',
    start: 7.53,
    end: 8.47,
    title: "You're My Playboy",
    charSprite1: 'char_playboy_1',
    charSprite2: 'char_playboy_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_playboy',
    textPos: { x: 0, y: 6 },
    animType: 'tilt_bob',
  },
  {
    id: 'playtoy',
    start: 8.47,
    end: 9.33,
    title: 'Playtoy Flower',
    charSprite1: 'char_flower_1',
    charSprite2: 'char_flower_2',
    charPos: { x: 0, y: 36 },
    textSprite: 'text_flower',
    textPos: { x: 0, y: 6 },
    animType: 'flower_spin',
  },
  {
    id: 'transitional_blank',
    start: 9.33,
    end: 10.80,
    title: 'Interlude (LCD)',
    charSprite1: 'char_twocats_1',
    charSprite2: 'char_twocats_2',
    charPos: { x: 0, y: 55 },
    textSprite: null,
    textPos: { x: 0, y: 0 },
    animType: 'interlude_blank',
  },
  {
    id: 'wanna_be',
    start: 10.80,
    end: 12.37,
    title: 'I Wanna Be With You',
    charSprite1: 'char_wanna_1',
    charSprite2: 'char_wanna_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_wanna',
    textPos: { x: 0, y: 6 },
    animType: 'duo_dance_props',
  },
  {
    id: 'until_end',
    start: 12.37,
    end: 14.73,
    title: 'Until The End',
    charSprite1: 'char_until_1',
    charSprite2: 'char_until_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_until',
    textPos: { x: 0, y: 6 },
    animType: 'duo_groove',
  },
  {
    id: 'give_heart',
    start: 14.73,
    end: 15.90,
    title: 'I Give My Heart',
    charSprite1: 'char_give_1',
    charSprite2: 'char_give_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_give',
    textPos: { x: 0, y: 6 },
    animType: 'heart_pose',
  },
  {
    id: 'soul_to_you',
    start: 15.90,
    end: 17.90,
    title: 'And My Soul To You',
    charSprite1: 'char_soul_1',
    charSprite2: 'char_soul_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_soul',
    textPos: { x: 0, y: 6 },
    animType: 'tongue_wink',
  },
  {
    id: 'knife_true',
    start: 17.90,
    end: 21.43,
    title: "To Make You See It's True",
    charSprite1: 'char_knife_1',
    charSprite2: 'char_knife_2',
    charPos: { x: 0, y: 45 },
    textSprite: 'text_knife',
    textPos: { x: 0, y: 6 },
    animType: 'knife_sway',
  },
  {
    id: 'confused',
    start: 21.43,
    end: 22.77,
    title: "I'm So Confused,",
    charSprite1: 'char_confused_1',
    charSprite2: 'char_confused_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_confused',
    textPos: { x: 0, y: 6 },
    animType: 'confused_sweat',
  },
  {
    id: 'cant_you_see',
    start: 22.77,
    end: 24.83,
    title: "Baby Can't You See?",
    charSprite1: 'char_deadpan_1',
    charSprite2: 'char_deadpan_2',
    charPos: { x: 0, y: 42 },
    textSprite: 'text_deadpan',
    textPos: { x: 0, y: 6 },
    animType: 'deadpan_blink',
  },
  {
    id: 'rescue_me',
    start: 24.83,
    end: 28.53,
    title: 'Please Come Rescue Me',
    charSprite1: 'char_rescue_1',
    charSprite2: 'char_rescue_2',
    charPos: { x: 0, y: 60 },
    textSprite: 'text_rescue',
    textPos: { x: 0, y: 6 },
    animType: 'rescue_crying',
  },
  {
    id: 'sweet_little',
    start: 28.53,
    end: 30.17,
    title: 'Sweet Little Bumblebee',
    charSprite1: 'char_sweet_1',
    charSprite2: 'char_sweet_2',
    charPos: { x: 0, y: 38 },
    textSprite: 'text_sweet',
    textPos: { x: 0, y: 6 },
    animType: 'finale_sing',
  },
  {
    id: 'know_what',
    start: 30.17,
    end: 30.93,
    title: 'I Know What You',
    charSprite1: 'char_singing_cat_20',
    charSprite2: 'char_sweet_2',
    charPos: { x: 0, y: 38 },
    textSprite: 'text_know_what',
    textPos: { x: 0, y: 6 },
    animType: 'finale_sing_sub',
  },
  {
    id: 'want_from_me',
    start: 30.93,
    end: 31.87,
    title: 'Want From Me',
    charSprite1: 'char_singing_cat_21',
    charSprite2: 'char_sweet_1',
    charPos: { x: 0, y: 38 },
    textSprite: 'text_want_from_me',
    textPos: { x: 0, y: 6 },
    animType: 'finale_hold',
  }
];

export function getSceneAt(time) {
  const t = Math.max(0, time);
  for (let i = 0; i < SCENES.length; i++) {
    const s = SCENES[i];
    if (t >= s.start && t < s.end) {
      return { scene: s, progress: (t - s.start) / (s.end - s.start), sceneIndex: i };
    }
  }
  // Clamp to last scene if past duration
  const last = SCENES[SCENES.length - 1];
  return { scene: last, progress: 1.0, sceneIndex: SCENES.length - 1 };
}
